/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import { FieldAuthorizeResolver } from "nexus/dist/plugins/fieldAuthorizePlugin"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  AuthPayload: { // root type
    token?: string | null; // String
    user?: NexusGenRootTypes['User'] | null; // User
  }
  Mutation: {};
  Query: {};
  Student: { // root type
    birthdate?: string | null; // String
    key?: string | null; // ID
    languages?: string | null; // String
    name?: string | null; // String
  }
  User: { // root type
    email?: string | null; // String
    isVerified?: boolean | null; // Boolean
    key?: string | null; // ID
    name?: string | null; // String
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  AuthPayload: { // field return type
    token: string | null; // String
    user: NexusGenRootTypes['User'] | null; // User
  }
  Mutation: { // field return type
    changePassword: NexusGenRootTypes['User'] | null; // User
    createStudent: NexusGenRootTypes['Student'] | null; // Student
    createUser: NexusGenRootTypes['AuthPayload'] | null; // AuthPayload
    deleteUser: NexusGenRootTypes['User'] | null; // User
    login: NexusGenRootTypes['AuthPayload'] | null; // AuthPayload
    updateUser: NexusGenRootTypes['User'] | null; // User
  }
  Query: { // field return type
    me: NexusGenRootTypes['User'] | null; // User
    student: NexusGenRootTypes['Student'] | null; // Student
    students: Array<NexusGenRootTypes['Student'] | null> | null; // [Student]
    user: NexusGenRootTypes['User'] | null; // User
    userCount: number | null; // Int
    users: Array<NexusGenRootTypes['User'] | null> | null; // [User]
  }
  Student: { // field return type
    birthdate: string | null; // String
    key: string | null; // ID
    languages: string | null; // String
    name: string | null; // String
  }
  User: { // field return type
    email: string | null; // String
    isVerified: boolean | null; // Boolean
    key: string | null; // ID
    name: string | null; // String
  }
}

export interface NexusGenFieldTypeNames {
  AuthPayload: { // field return type name
    token: 'String'
    user: 'User'
  }
  Mutation: { // field return type name
    changePassword: 'User'
    createStudent: 'Student'
    createUser: 'AuthPayload'
    deleteUser: 'User'
    login: 'AuthPayload'
    updateUser: 'User'
  }
  Query: { // field return type name
    me: 'User'
    student: 'Student'
    students: 'Student'
    user: 'User'
    userCount: 'Int'
    users: 'User'
  }
  Student: { // field return type name
    birthdate: 'String'
    key: 'ID'
    languages: 'String'
    name: 'String'
  }
  User: { // field return type name
    email: 'String'
    isVerified: 'Boolean'
    key: 'ID'
    name: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    changePassword: { // args
      newPassword: string; // String!
      oldPassword: string; // String!
    }
    createStudent: { // args
      birthdate?: string | null; // String
      languages?: string | null; // String
      name?: string | null; // String
    }
    createUser: { // args
      email: string; // String!
      name?: string | null; // String
      password: string; // String!
    }
    deleteUser: { // args
      key: string; // ID!
    }
    login: { // args
      email: string; // String!
      password: string; // String!
    }
    updateUser: { // args
      email?: string | null; // String
      key: string; // ID!
      name?: string | null; // String
    }
  }
  Query: {
    student: { // args
      key?: string | null; // ID
    }
    user: { // args
      key: string; // ID!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    /**
     * Authorization for an individual field. Returning "true"
     * or "Promise<true>" means the field can be accessed.
     * Returning "false" or "Promise<false>" will respond
     * with a "Not Authorized" error for the field.
     * Returning or throwing an error will also prevent the
     * resolver from executing.
     */
    authorize?: FieldAuthorizeResolver<TypeName, FieldName>
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}